language: python

python:
    - "2.7"
    #- "3.3" # matplotlib requires Python 3.4 or later
    - "3.4" 
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - jupyter nbextension enable --py --sys-prefix pythreejs
    - pip install .
    - pip install --quiet coverage
    - pip install --quiet coveralls

script:
    - nosetests -v --nocapture --with-doctest --with-coverage --exe --cover-package=pandas3js

after_success:
    - coveralls

deploy:
    # test pypi
  - provider: pypi
    distributions: bdist_wheel 
    server: https://testpypi.python.org/pypi
    user: cjsewell
    password:
      secure: ssuQpbMExfbnkN9EB3z9Y8YxJtC3k37OpLMtvetl31/PZ8cOkjO4E5YewhHXnn2KNwIrjEXGocA29D89Jy39GU1HUqgIuoxpIrOPV6cPoOwJb8hGSkp3kJ84ep0Xf/QSUzYEyMGjWZwdTWtgklHHZjrL7LCCO2N6qL1P1RHpZu2Jd9SIjnsEZP6QQ8oBhZVnxZvdrG3oFHQ8NBwGUJ1m+eYdU58/+xhYLx71ADQy4Ifaq/01z39An3tkWIVG4nV6lwIhCAAWk5F0kAOd1JT5rjYzEosuNHvClCAfTW0uKTQMK85H4AICV6n6xY4HprSiVXSr02i1ES9YT65w5xBhCJHxRpHw+kFL6bVQMGigXhU0tzpI1ORWlnHi0W+v42sWJyOrOua37EU2IR02d4agsIiaOIm27YY40xuJNMf01Ggd6K7BLdKuP4PiY67hdEmJKnQKgjL0RqIR3yLZ1Ms1i5f/qIqphFXM3IoDRSIjT7WVo91xm+x8nHHDGX7Jv+DwVx8bh22mw/JwgjT5TImD4q84tw93mvkUd3v6Xe/lPuoji2UtJLo3tHs/rMj2vv3tRREwAmZWwvMUX5beIMpNVvlunmzIcUGZiKhkvpmaWEr3vIZ9vZxA9D3stDm4bFBOlaQGJ0hXnj/8z7iz6N1k/I1vB+VAVWRq2DWo8WrSK8I=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: bdist_wheel
    user: cjsewell
    password:
      secure: AyFtpNKWVUyj1H+ZIFLcwTdq7SWUmEKcuOXkr/FxvbtNNcRdasZ9wbeJb+50olMytlaWnQ19g5vRg//mkAeuJphwWrsdNU0PF/m2TG7Aj3TisTEngRQ5oegxhRvywso6dBq6333EIdFZSBq3Db0+bJ0WvDVl1rzAwHXzaLAk+lQfl9nTbzbg3FQV+mMj6H9jFkBlAB3ASStJAa6KXLWqdiB6IpIm/+MHYva6wTYETjBT9kEMrcBO9nnV/TzUbMQAD4fIvpeJH0BiJLStS6rcMASSU8Ofj3NfpwvjjXaLoU+isbcz5AGXXRxGxg0ZRoZbEZBAFMYvW3j7RWqQPekyR53wM9VoYuo5ygxzYvyEVvINcwvOoxC+ax9sEFJ6Yrhp/6IyT4Ff3v55N6my3ChaNV26QkoSP1nnMM4sObERD7WGW7+qHA6YIInt53r7wai8Bgl63zHXA0x1EgZpLtu7Vn9FD4hnzxinXG6iHIiY78eKxC0K5/2tTv/k9wrkI3hfJ3llSi53ruO7NftlvKJ8AwK9vk3HaXXHo7Ao1DhK2mKu27bKrcR0JlQw8cZglNWtqtUiA/jhBMY120n7j2/fiCzxDwBtG4nrXWHAZMI+fBzGHobV+ffemCLJoFldo0agGl4JLowqU7z55y7ytbvuycFYIaWiiG9scb7/XrHflxo=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
