language: python

python:
    - "2.7"
    #- "3.3" # matplotlib requires Python 3.4 or later
    - "3.4" 
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - jupyter nbextension enable --py --sys-prefix pythreejs
    - pip install .
    - pip install --quiet coverage
    - pip install --quiet coveralls

script:
    - nosetests -v --nocapture --with-doctest --with-coverage --exe --cover-package=pandas3js

after_success:
    - coveralls

deploy:
    # test pypi
  - provider: pypi
    distributions: bdist_wheel 
    server: https://testpypi.python.org/pypi
    user: cjsewell
    password:
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: bdist_wheel
    password:
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
